name: deploy test

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set environment variable (for tput command)
      run: echo "TERM=xterm" >> $GITHUB_ENV

    - name: Run install script
      run: |
        sudo chmod 555 ./a.sh
        sudo bash +x ./a.sh -c ./testdev.txt
